import { useState } from 'react'
import { CircleMarker, MapContainer, Polyline, TileLayer, Tooltip } from 'react-leaflet'
import { BusFront, ChevronLeft, Clock3, ExternalLink, MapPin, TrainFront } from 'lucide-react'
import { Link } from 'react-router-dom'
import 'leaflet/dist/leaflet.css'
import { METRO_LINES, METRO_STATIONS, TRANSIT_SOURCES } from '../data/transitData'

function MetroTransit() {
  const [selected, setSelected] = useState(METRO_STATIONS[0])
  return <main className="min-h-screen bg-[#f8f4ec] p-4 text-burgundy-dark md:p-7"><div className="mx-auto max-w-[92rem]"><header className="flex flex-wrap items-center justify-between gap-4"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-burgundy hover:underline"><ChevronLeft size={17} />Dashboard</Link><div className="flex items-center gap-2 text-xs"><a className="inline-flex items-center gap-1 rounded-full border border-burgundy/20 bg-white px-3 py-2 text-burgundy" href={TRANSIT_SOURCES.metroNetwork} target="_blank" rel="noreferrer">Official DMRC map <ExternalLink size={13} /></a><a className="inline-flex items-center gap-1 rounded-full border border-burgundy/20 bg-white px-3 py-2 text-burgundy" href={TRANSIT_SOURCES.busTimetable} target="_blank" rel="noreferrer">DTC timetable <ExternalLink size={13} /></a></div></header><section className="mt-4 rounded-[2rem] bg-gradient-to-r from-[#4c1728] via-[#67283d] to-[#34101d] p-6 text-cream md:p-8"><div className="flex items-start gap-3"><span className="rounded-2xl bg-gold/20 p-3 text-gold"><TrainFront size={25} /></span><div><p className="text-xs font-semibold tracking-[.18em] text-gold">PUBLIC TRANSPORT</p><h1 className="mt-1 font-display text-4xl font-bold">Delhi Metro & bus connections</h1><p className="mt-2 max-w-3xl text-sm text-cream/70">Choose a station on the map to see the lines, service window, nearby bus stop, and route numbers.</p></div></div></section>

      <section className="mt-6 grid gap-5 xl:grid-cols-[1fr_22rem]"><div className="metro-map-shell overflow-hidden rounded-[2rem] border border-burgundy/10 bg-white shadow-sm"><MapContainer center={[28.64, 77.19]} zoom={10} minZoom={8} maxZoom={14} className="metro-leaflet-map"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{METRO_LINES.map((line) => <Polyline key={line.name} positions={line.points} pathOptions={{ color: line.color, weight: 5, opacity: 0.86 }} />)}{METRO_STATIONS.map((station) => <CircleMarker key={station.name} center={station.position} radius={selected.name === station.name ? 9 : 6} pathOptions={{ color: '#fffdf7', weight: 2, fillColor: '#5b2439', fillOpacity: 1 }} eventHandlers={{ click: () => setSelected(station) }}><Tooltip direction="top" offset={[0, -7]}>{station.name}</Tooltip></CircleMarker>)}</MapContainer><div className="flex flex-wrap gap-x-4 gap-y-2 border-t border-burgundy/10 bg-[#fffdf9] px-5 py-3">{METRO_LINES.map((line) => <span key={line.name} className="flex items-center gap-1.5 text-[11px] font-semibold text-burgundy-dark/70"><i className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: line.color }} />{line.name}</span>)}</div></div>
        <aside className="rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-burgundy/10"><p className="text-xs font-bold uppercase tracking-[.16em] text-burgundy">Selected station</p><h2 className="mt-2 font-display text-3xl font-bold">{selected.name}</h2><div className="mt-5"><p className="text-xs font-semibold uppercase tracking-wider text-burgundy-dark/50">Metro lines</p><div className="mt-2 flex flex-wrap gap-2">{selected.lines.map((line) => <span key={line} className="rounded-full bg-[#f7e4e7] px-3 py-1 text-xs font-semibold text-burgundy">{line}</span>)}</div></div><div className="mt-5 rounded-2xl bg-[#fff8e8] p-4"><p className="flex items-center gap-2 text-sm font-semibold text-[#7c5310]"><Clock3 size={16} />Service window</p><p className="mt-2 text-sm text-burgundy-dark/70">First train: <strong>{selected.first}</strong></p><p className="mt-1 text-sm text-burgundy-dark/70">Last train: <strong>{selected.last}</strong></p></div><div className="mt-5"><p className="flex items-center gap-2 text-sm font-semibold"><BusFront size={17} className="text-burgundy" />Nearest bus station</p><p className="mt-1 flex items-center gap-1 text-sm text-burgundy-dark/65"><MapPin size={14} />{selected.busStop}</p><p className="mt-3 text-xs font-semibold uppercase tracking-wider text-burgundy-dark/50">Available routes</p><div className="mt-2 flex flex-wrap gap-2">{selected.buses.map((bus) => <span key={bus} className="rounded-lg bg-[#e9f1fb] px-2.5 py-1 text-xs font-bold text-[#26578d]">{bus}</span>)}</div></div><a href={TRANSIT_SOURCES.busTimetable} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-burgundy hover:underline">Check current DTC schedule <ExternalLink size={15} /></a></aside></section>
      <p className="mt-5 text-xs leading-5 text-burgundy-dark/55">Network reference: DMRC’s current network map. Station, route, and timetable data are sourced from Delhi Government Open Transit Data and DTC; service information can change, so use the linked official timetable before travel.</p></div></main>
}

export default MetroTransit
